name: Deploy AWS
on:
  # manually trigger the workflow
   workflow_dispatch:
   workflow_run:
     workflows:
       - Build and Push Docker Image
#   push:
#     paths:
#       - 'my-house24-admin/**'
#       - 'my-house24-cabinet/**'
#       - 'my-house24-rest/**'
#       - 'my-house24-web-site/**'

jobs:
  build-docker-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: |
            my-house24-aws:latest
            my-house24-aws:${{ github.sha }}

  deploy-aws:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: build-docker-images
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd my-house24-aws
            docker compose pull
            docker compose up -d