name: Build and Push Admin Docker Image
on:
  push:
    branches:
      - main
      - dev-aws
    paths:
      - 'my-house24-rest/**'
jobs:
  build:
    name: Build and Push Docker Image for my-house24-rest
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.2.0
        env:
          MYSQL_ROOT_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          MYSQL_DATABASE: ${{secrets.DATABASE_NAME}}
          MYSQL_USER: ${{secrets.DATABASE_USERNAME}}
          MYSQL_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Adding secret
        env:
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        run: |
          envsubst < my-house24-rest/src/main/resources/application-temp.yml > my-house24-rest/src/main/resources/application.yml

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        run: cd my-house24-rest && mvn test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./my-house24-rest/Dockerfile
          push: true
          tags: olx09/my-house24-rest:latest