name: Build and Push Web Site Docker Image
on:
  push:
    branches:
      - main
      - dev-aws
    paths:
      - 'my-house-24-web-site/**'
jobs:
  build:
    name: Build and Push Docker Image for my-house24-web-site
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.2.0
        env:
          MYSQL_ROOT_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          MYSQL_DATABASE: ${{secrets.DATABASE_NAME}}
          MYSQL_USER: ${{secrets.DATABASE_USERNAME}}
          MYSQL_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Adding secret
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECREST_ACCESS_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        run: |
          envsubst < my-house-24-web-site/src/main/resources/application-temp.yml > my-house-24-web-site/src/main/resources/application.yml

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        run: cd my-house-24-web-site && mvn test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./my-house-24-web-site/Dockerfile
          push: true
          tags: olx09/my-house24-web-site:latest

  notify:
    name: Pull and Run web-site container
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 3m
          debug: true
          script: |
            echo "Start pull and restart container"
            cd /home/ubuntu/ && sudo docker compose -f docker-compose.yml pull && sudo docker compose -f docker-compose.yml restart my-house24-ol-ar-web-site
            echo "Container has been updated and is running"
            exit